services:
  openlist:
    image: 'openlistteam/openlist:latest'
    container_name: openlist
    user: '0:0'
    volumes:
      - './data:/opt/openlist/data'
    ports:
      - '5244:5244'
    environment:
      - UMASK=022
    restart: unless-stopped
